<?php

namespace common\base;


use backend\models\Admin;
use common\models\base\OperationLog;
use common\tools\Code;
use common\traits\BaseAction;
use Yii;
use yii\rest\ActiveController;

class BaseController extends ActiveController
{
    use BaseAction;
    public $modelClass = OperationLog::class;//默认一个值
    public $id ;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $headers = Yii::$app->request->headers;
        $token = $headers['x-token'];
        if (!$token) {
            echo json_encode(['code' => Code::getTokenCode(), 'message' => '请检查Token重试']);
            exit();
        }
        $token = base64_decode($token);
        $tokenArray = explode(':&:', $token);
        if ($tokenArray[1] < time()) {
            echo json_encode(['code' => Code::getTokenCode(), 'message' => '登陆过期请从新登陆']);
            exit();
        }
        if (Yii::$app->id === 'love-backend') {
            $redisKey = "AdminLoginToken" . $tokenArray[2];
            $this->modelClass = Admin::class;
        } else {
            $redisKey = "MemberLoginToken" . $tokenArray[2];
            $this->modelClass = Admin::class;
        }
        $info = Yii::$app->redis->get($redisKey);
        if (!$info) {
            echo json_encode(['code' => Code::getTokenCode(), 'message' => '登陆过期请从新登陆']);
            exit();
        }
        $info = $this->modelClass::findIdentity($tokenArray[2]);
        if ((int)$info->status !== 1){
            echo json_encode(['code' => Code::getTokenCode(), 'message' => '该账号状态异常']);
            exit();
        }
        Yii::$app->user->login($info);
        $this->id = $info->id;
    }
}
